[project]
name = "agentsmcp"
version = "1.0.0"
description = "CLI-driven MCP agent system with extensible RAG pipeline"
requires-python = ">=3.11"
dependencies = [
    "click>=8.0",
    "fastapi>=0.104",
    "uvicorn>=0.24",
    "pydantic>=2.0",
    "pyyaml>=6.0",
]

[project.scripts]
agentsmcp = "agentsmcp.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.2",
    "pytest-cov>=5.0",
    "pytest-asyncio>=0.24",
    "ruff>=0.4",
    "bandit>=1.7",
    "pip-audit>=2.7",
]
rag = [
    "sentence-transformers>=2.2",
    "numpy>=1.24",
]

[tool.pytest.ini_options]
addopts = "--cov=agentsmcp --cov-fail-under=80"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.bandit]
skips = ["B101"]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["agentsmcp*"]