#!/bin/bash
# AgentsMCP Quick Start Script for M4 MacBook

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 AgentsMCP Quick Start${NC}"
echo "==============================="

# JWT_SECRET is now auto-generated by the application for local development
echo -e "${GREEN}✓${NC} JWT secret will be auto-generated for this session"

# Check if package is installed
if ! command -v agentsmcp &> /dev/null; then
    echo -e "${YELLOW}📦 Installing AgentsMCP...${NC}"
    pip install -e . --quiet
    echo -e "${GREEN}✓${NC} Installation complete"
fi

# Launch with appropriate settings for M4
echo -e "${GREEN}✨ Launching AgentsMCP Interactive CLI${NC}"
echo -e "${YELLOW}Tip: Press Ctrl+C to exit at any time${NC}"
echo ""

# Start the interactive CLI
agentsmcp interactive --theme auto