{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agentsmcp.fullname" . }}-default-deny-all
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: security
spec:
  podSelector:
    matchLabels:
      {{- include "agentsmcp.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress

---
{{- if .Values.networkPolicy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agentsmcp.fullname" . }}-ingress-allowed
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: security
spec:
  podSelector:
    matchLabels:
      {{- include "agentsmcp.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
  - Ingress
  ingress:
  {{- with .Values.networkPolicy.ingress.from }}
  - from:
    {{- toYaml . | nindent 4 }}
    ports:
    - protocol: TCP
      port: 8000
  {{- end }}
  # Allow health checks from kubelet
  - from: []
    ports:
    - protocol: TCP
      port: 8000
  # Allow pod-to-pod communication within namespace
  - from:
    - podSelector:
        matchLabels:
          {{- include "agentsmcp.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8000
{{- end }}

---
{{- if .Values.networkPolicy.egress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agentsmcp.fullname" . }}-egress-allowed
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: security
spec:
  podSelector:
    matchLabels:
      {{- include "agentsmcp.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP for health checks and APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
  {{- with .Values.networkPolicy.egress.to }}
  # Custom egress rules
  - to:
    {{- toYaml . | nindent 4 }}
    ports:
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 3306  # MySQL
  {{- end }}
  # Allow pod-to-pod communication within namespace
  - to:
    - podSelector:
        matchLabels:
          {{- include "agentsmcp.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8000
{{- end }}
{{- end }}