{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentsmcp.secretName" . }}
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: secrets
  annotations:
    secret.agentsmcp.io/rotation-policy: "90d"
    secret.agentsmcp.io/created-by: "helm-chart"
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.ingress.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentsmcp.fullname" . }}-tls
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.cert | default "PLACEHOLDER_TLS_CRT_BASE64" }}
  tls.key: {{ .Values.ingress.tls.key | default "PLACEHOLDER_TLS_KEY_BASE64" }}
{{- end }}

{{- if .Values.image.pullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentsmcp.fullname" . }}-registry
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecrets.dockerconfigjson | default "PLACEHOLDER_DOCKER_CONFIG_JSON_BASE64" }}
{{- end }}