{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentsmcp.serviceAccountName" . }}
  namespace: {{ include "agentsmcp.namespace" . }}
  labels:
    {{- include "agentsmcp.labels" . | nindent 4 }}
    component: serviceaccount
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}