"""Data models for CLI v3 command engine."""

from .command_models import (
    ExecutionMode,
    SkillLevel, 
    CommandStatus,
    ResourceType,
    UserProfile,
    UserPreferences,
    ResourceLimit,
    CommandRequest,
    CommandResult,
    ExecutionMetrics,
    NextAction,
    Suggestion,
    CommandError,
    AuditLogEntry,
    CommandEngineError,
    CommandNotFoundError,
    ValidationFailedError,
    ExecutionTimeoutError,
    PermissionDeniedError,
    ResourceExhaustedError,
)

from .coordination_models import (
    InterfaceMode,
    SyncStatus,
    ConflictResolution,
    CapabilityType,
    Feature,
    SessionContext,
    StateChange,
    ConflictInfo,
    SharedState,
    ModalSwitchRequest,
    StateSync,
    CapabilityQuery,
    TransitionResult,
    SyncResult,
    CapabilityInfo,
    CoordinationError,
    SyncFailedError,
    ModeNotSupportedError,
    StateLossError,
    CapabilityMismatchError,
    ConflictResolutionError,
)

__all__ = [
    # Command models
    "ExecutionMode",
    "SkillLevel",
    "CommandStatus", 
    "ResourceType",
    "UserProfile",
    "UserPreferences",
    "ResourceLimit",
    "CommandRequest",
    "CommandResult", 
    "ExecutionMetrics",
    "NextAction",
    "Suggestion",
    "CommandError",
    "AuditLogEntry",
    "CommandEngineError",
    "CommandNotFoundError",
    "ValidationFailedError",
    "ExecutionTimeoutError",
    "PermissionDeniedError",
    "ResourceExhaustedError",
    # Coordination models
    "InterfaceMode",
    "SyncStatus",
    "ConflictResolution",
    "CapabilityType",
    "Feature",
    "SessionContext",
    "StateChange",
    "ConflictInfo",
    "SharedState",
    "ModalSwitchRequest",
    "StateSync",
    "CapabilityQuery",
    "TransitionResult",
    "SyncResult",
    "CapabilityInfo",
    "CoordinationError",
    "SyncFailedError",
    "ModeNotSupportedError",
    "StateLossError",
    "CapabilityMismatchError",
    "ConflictResolutionError",
]