name: Automerge

on:
  pull_request_target:
    types:
      - labeled
      - closed

jobs:
  enable-automerge:
    if: github.event.action == 'labeled' && github.event.label.name == 'automerge'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash

  delete-branch:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`,
            });
