name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      AGENTSMCP_TEST_MODE: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff Lint
        run: |
          python -m pip install ruff
          ruff check src

      - name: Run tests (mock mode)
        run: |
          pytest -q

      - name: Upload coverage
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./.coverage

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: agentsmcp:ci
